@startuml
ditaa
-------------------+---------------------------------------+------------- 사내망
                   ^                                       ^
                   |                                       |
                   v                                       |
/------------------+-------------------\                   v
|               My router              |        +----------+------------+
|                                      |        |cGREDevelopment server |
|           IP ex) 172.16.7.XXX        |        |                       |
|           DNS ex) 10.1.1.25          |        |    IP ex) 172.16.7.YYY|
|                                      |        |    DNS ex) 10.1.1.25  |
|    Internal DHCP server) 192.168.0.1 |        \-----------------------/
\--------+-------------------+---------/
         ^                   ^
         |                   |
         v                   v
+--------+--------+ +--------+---------+
|      My PC      | |cPNKTarget device |
|                 | |                  |
| ex) 192.168.0.X | | ex) 192.168.0.XXX|
+--------+--------+ +------------------+
         ^
         :
         |
         v
+--------+--------+
|cYEL My WSL      |
|                 |
|ex) 192.168.0.100|
\-----------------/
@enduml